[platformio]
default_envs = c3

[env:c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DCORE_DEBUG_LEVEL=3
