[platformio]
default_envs = base, head

[env:base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
build_unflags = -std=gnu++11 -std=gnu++17
build_flags =
  -std=gnu++20
  -DARDUINO_USB_CDC_ON_BOOT=0
  -Ivendor/base/lib/GfxRenderer

[env:head]
extends = env:base
build_flags =
  -std=gnu++20
  -DARDUINO_USB_CDC_ON_BOOT=0
  -Ivendor/head/lib/GfxRenderer
