[platformio]
default_envs = c3

[env:c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
build_src_filter = +<*> -<pr/*>
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DCORE_DEBUG_LEVEL=3

[env:c3_df]
extends = env:c3
build_src_filter = +<*>
build_flags =
  ${env:c3.build_flags}
  -DLAB_TCP_DF=1
  -Isrc/pr

[env:c3_edges]
extends = env:c3
build_flags =
  ${env:c3.build_flags}
  -DLAB_PACKET_EDGES=1

[env:c3_df_edges]
extends = env:c3_df
build_flags =
  ${env:c3_df.build_flags}
  -DLAB_PACKET_EDGES=1
